// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOPEcJ_lLQJ0DLQVI2qM8D5m14GqzjUFI',
    appId: '1:199647764096:web:def7415641dac2cb411065',
    messagingSenderId: '199647764096',
    projectId: 'reservas-pinheiro-society',
    authDomain: 'reservas-pinheiro-society.firebaseapp.com',
    storageBucket: 'reservas-pinheiro-society.firebasestorage.app',
    measurementId: 'G-QDBPYLXCG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC46eu2FthZVMIM6oVNeGlMbZa15-kmZgo',
    appId: '1:199647764096:android:5947a72d95f1ba4d411065',
    messagingSenderId: '199647764096',
    projectId: 'reservas-pinheiro-society',
    storageBucket: 'reservas-pinheiro-society.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGDZY2kBws3aT_bHrs-CJRBMFDjzpGsT0',
    appId: '1:199647764096:ios:36810c72f431c631411065',
    messagingSenderId: '199647764096',
    projectId: 'reservas-pinheiro-society',
    storageBucket: 'reservas-pinheiro-society.firebasestorage.app',
    iosBundleId: 'com.example.reservasPinheirosociety',
  );
}
